server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Bastian444/Proyecto-Tingeso-2
          search-paths: config-data
  application:
    name: config_server

